crnk:
  path-prefix: /api
  security:
    enabled: false
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    url: jdbc:postgresql://localhost:5433/postgres
#    username: postgres
#    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/main.xml

security:
  enabled: ${SECURITY_ENABLED:true}
  jwt:
    key-store: classpath:security/cards.jks
    key-store-password: changeit
    key-pair-alias: offer
    key-pair-password: changeit
    public-key: classpath:security/public.txt
