version: '3'
services:

  app:
    build: .
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    ports:
      - 8080:8080
    command: bash -c "gradle --no-daemon clean copyDocumentationToResources build && java -jar ./build/libs/*.jar"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    #    ports:
    #      - "5432:5432"
    restart: unless-stopped

volumes:
  data:
